### ISSUE TITLE
Windows Users: Folders security settings and Devices

### ISSUE THREAD

**Issue by circuitb** [tomduncalf/ubermap#1]
hey there,
this is really nice project!

regarding windows(8) users:
you have to change the security settings for all the created folders
i put Read/Write access to "Everyone" in the security tab (right clic folder)
for both
C:\Users\Tom\Ubermap
C:\ProgramData\Ableton\Live 9 Suite\Resources\MIDI Remote Scripts
at this point you can see the created "device_HASH.cfg" files  and edit them!

now the issue
i've just edited the cfg file for the Midi Scale device
just inverting the first two parameters
the created cfg include a 
[BestOfBank]
[[Bank]] tag ...not sure what is it exactly...
but when i modify the file... just swap parameters position
the inverted parameters are blank (no name, no values) on the push, so here is the original  working generated cfg file for the Scale Midi Device:

[Banks]
[[Bank 1]]
1_Base = Base
2_Transpose = Transpose
3_Fold = Fold
4_Lowest = Lowest
5_Range = Range
6_Map 0 = Map 0
7_Map 1 = Map 1
8_Map 2 = Map 2
[[Bank 2]]
9_Map 3 = Map 3
10_Map 4 = Map 4
11_Map 5 = Map 5
12_Map 6 = Map 6
13_Map 7 = Map 7
14_Map 8 = Map 8
15_Map 9 = Map 9
16_Map 10 = Map 10
[[Bank 3]]
17_Map 11 = Map 11
[BestOfBank]
[[Bank]]
1_Base = Base
2_Transpose = Transpose
3_Fold = Fold
4_Lowest = Lowest
5_Range = Range
6_Map 0 = Map 0
7_Map 1 = Map 1
8_Map 2 = Map 2
[Config]
Cache = False
Ignore = True

and the edited  non  Working One:

[Banks]
[[Bank 1]]
2_Base = Base
1_Transpose = Transpose
3_Fold = Fold
4_Lowest = Lowest
5_Range = Range
6_Map 0 = Map 0
7_Map 1 = Map 1
8_Map 2 = Map 2
[[Bank 2]]
9_Map 3 = Map 3
10_Map 4 = Map 4
11_Map 5 = Map 5
12_Map 6 = Map 6
13_Map 7 = Map 7
14_Map 8 = Map 8
15_Map 9 = Map 9
16_Map 10 = Map 10
[[Bank 3]]
17_Map 11 = Map 11
[BestOfBank]
[[Bank]]
2_Base = Base
1_Transpose = Transpose
3_Fold = Fold
4_Lowest = Lowest
5_Range = Range
6_Map 0 = Map 0
7_Map 1 = Map 1
8_Map 2 = Map 2
[Config]
Cache = False
Ignore = False

the first two parameters are blank on the push!

btw i had success modifying a M4L cfg for the Note Echo.amxd
[Banks]
[[Bank 1]]
2_Feed Delay = Feed Delay
1_Beat Division = Beat Division
3_Feedback = Feedback
4_Ms Delay = Ms Delay
5_Pitch = Pitch
6_Thru/Mute = Thru/Mute
7_Delay Mode = Delay Mode
8_Beat Offset Percentage = Beat Offset Percentage
[BestOfBank]
[[Bank]]
[Config]
Cache = False
Ignore = False

strange! any ideas??
thanks

**Comment by tomduncalf** [comment]
Closing this as its old, apologies for not responding - please open a new issue if required
