### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by circuitb** [tomduncalf/ubermap#2]
hi again,
i'm wondering if with those custom midi remote control scripts
it's  somehow possible to parse device parameters name's to push in rel time?
i mean lets say i've a generic m4l device with 4 dials named dial1, dial2 etc...
on two different tracks and i want to change dial1 name on track 1 to something like
Trk1_Dial1 (receiving the string name through Osc for example)
of course without reloading the device!
sounds possible to you?

thx

**Comment by circuitb** [comment]
okay it's possible... but with some huge workarounds... at least on windows
see here:
https://forum.ableton.com/viewtopic.php?f=55&t=201849&p=1664924#p1664924

**Comment by tomduncalf** [comment]
Closing this as its old, apologies for not responding - please open a new issue if required
