### ISSUE TITLE
Can't change parameter names in with Push 2 Live 9.6.2b1

### ISSUE THREAD

**Issue by djdesjardins2000** [tomduncalf/ubermap#4]
Thanks Tom.  This is my first time using Ubermap.  I can change the Bank names and even create new Banks and also reorder parameters in the .cfg files but when I make changes to the names ( the one after the = ) nothing changes.  Any ideas what I might be doing wrong. Push 2 Live 9.6.2b1 El Capitan.

Thanks.

**Comment by tomduncalf** [comment]
Hey, it's actually possible this feature isn't working! I didn't have time to test it thoroughly and don't use parameter renaming much myself. I'll check it out and let you know!

**Comment by tomduncalf** [comment]
Yeah, looks like this isn't working on Push 2, unfortunately not sure why! Will try and have a look into it at some point.

**Comment by djdesjardins2000** [comment]
Thanks.

**Comment by tomduncalf** [comment]
This should now work on Push 2

**Comment by djdesjardins2000** [comment]
Yes.  Thank you.
