### ISSUE TITLE
Can I use LuSH-101 mapping for my project ?

### ISSUE THREAD

**Issue by jhorology** [tomduncalf/ubermap#5]
Sorry, this is not a issue. I couldn't find your contact address. I want to use your LuSH-101 mapping for my project, because I'm also using push 2, and I will try this software in the near future.
https://github.com/jhorology/nks-presets-collection

If it's possible, is it require license notice or something ? Now I'm reading Creative Commons...4.0 license. It's greek to me.

**Comment by tomduncalf** [comment]
Hey, sure, go ahead :)

**Comment by jhorology** [comment]
Thank you!
